on:
  push

name: SonarQube

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: |
            echo "Hello World"
            ./run.sh
  sonarqube: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Build and SonarCloud Scan
        with:
          gradle-version: 7.6
        run: gradle build sonarqube --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
