on:
  push

name: SonarQube

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: |
            echo "Hello World"
            ./run.sh

  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew
    - name: Build and analyze
      run: ./gradlew build sonarqube \
          -Dsonar.projectKey=nypag-1_uk-223 \
          -Dsonar.organization=YOUR_ORG_KEY \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
