on:
  push

name: SonarQube

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: |
            echo "Hello World"
            ./run.sh

  sonarqube: 
    runs-on: ubuntu--latest
    steps: 
      - uses: sonarsource/sonarcloud-github-action@v3
        with:
          projectBaseDir: app/src
          args: >
            -Dsonar.organization=nypag-1
            -Dsonar.projectKey=nypag-1_uk-223
            -Dsonar.verbose=true
            -Dsonar.token=92d1ecda325d3ff2db32d35611091f1ce7ba79b9
