on:
  push

name: SonarQube

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: |
            echo "Hello World"
            ./run.sh

  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew
    - name: Build and Scan with SonarQube
      run: ./gradlew build sonarqube
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
